### ISSUE TITLE
Bug with soften class

### ISSUE THREAD

**Issue by madtomic** [Di3mex/ExtraHardMode#33]
Hello,

Why is cobblestone is still consider as soft rocks?

I already changed to this.
        - STONE-GRAVEL

Do you think you could fix the bug with cobblestone being hardcoded for stone soften into?

I want to use Gravel but Cobblestone are still falling like soften stones.

Thanks,
madtomic

**Comment by Di3mex** [comment]
Stone Blocks (Stone@data-Cobble@data):
- STONE-GRAVEL

When I set this smooth stone softens to gravel. The falling sand looks like gravle and when it lands it is still gravle. Isn't that the expected output?

**Comment by madtomic** [comment]
I found out this was affect by Additional Falling Blocks. Thanks for getting back!
